export type VisualAssetCategory =
  | "editorial"
  | "epk"
  | "lookbook"
  | "cinematic"
  | "cover";

export type VisualAsset = {
  id: string;
  label: string;
  category: VisualAssetCategory;
  purpose: string;
  src: string;
  orientation: "landscape" | "portrait" | "square";
  tags: string[];
};

/**
 * Managed Visual DNA library. These are intentionally referenced by their
 * managed storage paths instead of bundled into the application build.
 */
export const VISUAL_DNA_ASSETS: VisualAsset[] = [
  {
    id: "reflection-closeup",
    label: "Chrome Reflection",
    category: "cover",
    purpose: "Premium cover-art fallback and hero detail crop.",
    src: "/manus-storage/01_44dfaa9f.png",
    orientation: "landscape",
    tags: ["chrome", "macro", "amber", "editorial"],
  },
  {
    id: "gold-chain-portrait",
    label: "Gold Chain Portrait",
    category: "epk",
    purpose: "Artist roster, EPK, and press portrait treatment.",
    src: "/manus-storage/02_8655b711.png",
    orientation: "portrait",
    tags: ["gold", "portrait", "streetwear", "luxury"],
  },
  {
    id: "jewel-shadow",
    label: "Jewel Shadow",
    category: "cover",
    purpose: "Dark cover-art filler with jewelry and editorial attitude.",
    src: "/manus-storage/03_58a5f98b.png",
    orientation: "portrait",
    tags: ["jewelry", "shadow", "saturated", "rap"],
  },
  {
    id: "blue-chrome-profile",
    label: "Blue Chrome Profile",
    category: "cinematic",
    purpose: "Cold-versus-warm cinematic contrast for video and sync concepts.",
    src: "/manus-storage/04_7df0a36f.png",
    orientation: "portrait",
    tags: ["chrome", "blue", "profile", "music-video"],
  },
  {
    id: "hype-collage-01",
    label: "Editorial Contact Sheet 01",
    category: "editorial",
    purpose: "Multi-panel editorial background for campaign surfaces.",
    src: "/manus-storage/Create_5_hip_hop_photography_styles_1._Hype_Williams_Style____0d5c2df8-be04-4285-a6be-7d358ba8e32d_1_b8c771f9.png",
    orientation: "landscape",
    tags: ["hype", "collage", "saturated", "campaign"],
  },
  {
    id: "hype-collage-02",
    label: "Editorial Contact Sheet 02",
    category: "editorial",
    purpose: "High-energy campaign background with multiple visual beats.",
    src: "/manus-storage/Create_5_hip_hop_photography_styles_1._Hype_Williams_Style____0d5c2df8-be04-4285-a6be-7d358ba8e32d_2_abf36eb1.png",
    orientation: "landscape",
    tags: ["hype", "collage", "amber", "campaign"],
  },
  {
    id: "hype-collage-03",
    label: "Editorial Contact Sheet 03",
    category: "editorial",
    purpose: "Hero backdrop or campaign board for the Visuals vault.",
    src: "/manus-storage/Create_5_hip_hop_photography_styles_1._Hype_Williams_Style____0d5c2df8-be04-4285-a6be-7d358ba8e32d_3_a9517e08.png",
    orientation: "landscape",
    tags: ["hype", "collage", "red", "campaign"],
  },
  {
    id: "hype-wide-01",
    label: "Hype Williams Board 01",
    category: "cinematic",
    purpose: "Cinematic music-video still board with glossy color separation.",
    src: "/manus-storage/Create_5_hip_hop_photography_styles_1._Hype_Williams_Style____a0f79e43-2f50-4839-b67d-0a3b006e2072_0_b8d23d57.png",
    orientation: "landscape",
    tags: ["hype", "cinematic", "red", "chrome"],
  },
  {
    id: "hype-wide-02",
    label: "Hype Williams Board 02",
    category: "cinematic",
    purpose: "Narrative still board for visual campaign exploration.",
    src: "/manus-storage/Create_5_hip_hop_photography_styles_1._Hype_Williams_Style____a0f79e43-2f50-4839-b67d-0a3b006e2072_1_379f01e5.png",
    orientation: "landscape",
    tags: ["hype", "cinematic", "orange", "street"],
  },
  {
    id: "hype-wide-03",
    label: "Hype Williams Board 03",
    category: "cinematic",
    purpose: "Visualizer and sync-pitch still board.",
    src: "/manus-storage/Create_5_hip_hop_photography_styles_1._Hype_Williams_Style____a0f79e43-2f50-4839-b67d-0a3b006e2072_2_0c659f23.png",
    orientation: "landscape",
    tags: ["hype", "cinematic", "teal", "portrait"],
  },
  {
    id: "hype-wide-04",
    label: "Hype Williams Board 04",
    category: "cinematic",
    purpose: "High-impact still board for narrative presentation.",
    src: "/manus-storage/Create_5_hip_hop_photography_styles_1._Hype_Williams_Style____a0f79e43-2f50-4839-b67d-0a3b006e2072_3_571f2106.png",
    orientation: "landscape",
    tags: ["hype", "cinematic", "cyan", "portrait"],
  },
  {
    id: "hype-red-01",
    label: "Red Editorial Board 01",
    category: "editorial",
    purpose: "Saturated red treatment for release campaigns and headline panels.",
    src: "/manus-storage/Create_5_hip_hop_photography_styles_1._Hype_Williams_Style____cc9157d9-470e-4f7b-8542-9813409e0985_0_1fe57b1a.png",
    orientation: "landscape",
    tags: ["red", "editorial", "flash", "campaign"],
  },
  {
    id: "hype-red-02",
    label: "Red Editorial Board 02",
    category: "editorial",
    purpose: "Luxury streetwear and rap campaign visual treatment.",
    src: "/manus-storage/Create_5_hip_hop_photography_styles_1._Hype_Williams_Style____cc9157d9-470e-4f7b-8542-9813409e0985_1_772e3088.png",
    orientation: "landscape",
    tags: ["red", "streetwear", "editorial", "gold"],
  },
  {
    id: "hype-red-03",
    label: "Red Editorial Board 03",
    category: "editorial",
    purpose: "Press kit background with direct-flash energy.",
    src: "/manus-storage/Create_5_hip_hop_photography_styles_1._Hype_Williams_Style____cc9157d9-470e-4f7b-8542-9813409e0985_2_64dc4f24.png",
    orientation: "landscape",
    tags: ["red", "press", "direct-flash", "portrait"],
  },
  {
    id: "hype-red-04",
    label: "Red Editorial Board 04",
    category: "editorial",
    purpose: "Premium release launch texture for cards and headers.",
    src: "/manus-storage/Create_5_hip_hop_photography_styles_1._Hype_Williams_Style____cc9157d9-470e-4f7b-8542-9813409e0985_3_b71bd0b0.png",
    orientation: "landscape",
    tags: ["red", "release", "editorial", "saturated"],
  },
  {
    id: "contact-sheet-01",
    label: "Hip-Hop Contact Sheet 01",
    category: "editorial",
    purpose: "Campaign collage for Visual DNA archive browsing.",
    src: "/manus-storage/Create_the_following_5_hip_hop_photography_styles_1._Hype_Wil_67fc9871-4d1b-4bf7-b5f4-c95c6648ac34_0_90a9a522.png",
    orientation: "landscape",
    tags: ["collage", "hip-hop", "campaign", "saturated"],
  },
  {
    id: "contact-sheet-02",
    label: "Hip-Hop Contact Sheet 02",
    category: "editorial",
    purpose: "Campaign collage with portrait, streetwear, and macro details.",
    src: "/manus-storage/Create_the_following_5_hip_hop_photography_styles_1._Hype_Wil_67fc9871-4d1b-4bf7-b5f4-c95c6648ac34_1_5ae8edf1.png",
    orientation: "landscape",
    tags: ["collage", "streetwear", "macro", "campaign"],
  },
  {
    id: "contact-sheet-03",
    label: "Hip-Hop Contact Sheet 03",
    category: "editorial",
    purpose: "Contact sheet for editorial direction and page backdrops.",
    src: "/manus-storage/Create_the_following_5_hip_hop_photography_styles_1._Hype_Wil_67fc9871-4d1b-4bf7-b5f4-c95c6648ac34_2_fd8c0d84.png",
    orientation: "landscape",
    tags: ["collage", "amber", "portrait", "campaign"],
  },
  {
    id: "contact-sheet-04",
    label: "Hip-Hop Contact Sheet 04",
    category: "editorial",
    purpose: "Dramatic style board for high-value artist positioning.",
    src: "/manus-storage/Create_the_following_5_hip_hop_photography_styles_1._Hype_Wil_67fc9871-4d1b-4bf7-b5f4-c95c6648ac34_3_441981be.png",
    orientation: "landscape",
    tags: ["collage", "blue", "cinematic", "artist"],
  },
  {
    id: "saturated-board-01",
    label: "Saturated Board 01",
    category: "lookbook",
    purpose: "Lookbook reference for high-fashion artist positioning.",
    src: "/manus-storage/httpss.mj.runG0VFuidrTN4_httpss.mj.runipORfeg3Amk_httpss.mj.r_e98aa9fc-4e23-463b-b461-37695c4befcd_0_c83f62c5.png",
    orientation: "landscape",
    tags: ["lookbook", "saturated", "jewelry", "streetwear"],
  },
  {
    id: "saturated-board-02",
    label: "Saturated Board 02",
    category: "lookbook",
    purpose: "High-energy streetwear and jewelry texture board.",
    src: "/manus-storage/httpss.mj.runG0VFuidrTN4_httpss.mj.runipORfeg3Amk_httpss.mj.r_e98aa9fc-4e23-463b-b461-37695c4befcd_1_d40b2d36.png",
    orientation: "landscape",
    tags: ["lookbook", "amber", "jewelry", "gloss"],
  },
  {
    id: "saturated-board-03",
    label: "Saturated Board 03",
    category: "lookbook",
    purpose: "Editorial streetwear presentation for artist and brand cards.",
    src: "/manus-storage/httpss.mj.runG0VFuidrTN4_httpss.mj.runipORfeg3Amk_httpss.mj.r_e98aa9fc-4e23-463b-b461-37695c4befcd_2_bdf0efd4.png",
    orientation: "landscape",
    tags: ["lookbook", "streetwear", "red", "portrait"],
  },
  {
    id: "saturated-board-04",
    label: "Saturated Board 04",
    category: "lookbook",
    purpose: "Visual reference for premium cover and roster treatments.",
    src: "/manus-storage/httpss.mj.runG0VFuidrTN4_httpss.mj.runipORfeg3Amk_httpss.mj.r_e98aa9fc-4e23-463b-b461-37695c4befcd_3_f68bd14c.png",
    orientation: "landscape",
    tags: ["lookbook", "blue", "chrome", "editorial"],
  },
  {
    id: "portrait-board-01",
    label: "Portrait Board 01",
    category: "epk",
    purpose: "Sharp portrait reference for press and EPK presentations.",
    src: "/manus-storage/httpss.mj.runGWUNuEW6ccE_httpss.mj.runjL-TLlkuR2A_httpss.mj.r_cc6ab512-7cb1-46be-bd4e-6d7905d2864f_0_86787777.png",
    orientation: "portrait",
    tags: ["epk", "portrait", "rim-light", "black"],
  },
  {
    id: "portrait-board-02",
    label: "Portrait Board 02",
    category: "epk",
    purpose: "High-contrast hero portrait for talent and roster cards.",
    src: "/manus-storage/httpss.mj.runGWUNuEW6ccE_httpss.mj.runjL-TLlkuR2A_httpss.mj.r_cc6ab512-7cb1-46be-bd4e-6d7905d2864f_1_38437b1c.png",
    orientation: "portrait",
    tags: ["epk", "portrait", "red", "rim-light"],
  },
  {
    id: "portrait-board-03",
    label: "Portrait Board 03",
    category: "epk",
    purpose: "Executive-ready talent portrait with controlled drama.",
    src: "/manus-storage/httpss.mj.runGWUNuEW6ccE_httpss.mj.runjL-TLlkuR2A_httpss.mj.r_cc6ab512-7cb1-46be-bd4e-6d7905d2864f_2_1a2d4e07.png",
    orientation: "portrait",
    tags: ["epk", "portrait", "shadow", "luxury"],
  },
  {
    id: "portrait-board-04",
    label: "Portrait Board 04",
    category: "epk",
    purpose: "Moody portrait reference for editorial and press surfaces.",
    src: "/manus-storage/httpss.mj.runGWUNuEW6ccE_httpss.mj.runjL-TLlkuR2A_httpss.mj.r_cc6ab512-7cb1-46be-bd4e-6d7905d2864f_3_5738f13f.png",
    orientation: "portrait",
    tags: ["epk", "portrait", "red", "cinematic"],
  },
  {
    id: "studio-profile-01",
    label: "Studio Profile 01",
    category: "epk",
    purpose: "Studio-session portrait treatment for producer and engineer profiles.",
    src: "/manus-storage/httpss.mj.runipORfeg3Amk_A_sharp_ultra-clean_professional_por_bac47d6a-2088-4f84-8e9d-9d6f691b2889_0_52b6ab3d.png",
    orientation: "portrait",
    tags: ["studio", "profile", "mixing", "epk"],
  },
  {
    id: "studio-profile-02",
    label: "Studio Profile 02",
    category: "epk",
    purpose: "Mix-room profile for professional production positioning.",
    src: "/manus-storage/httpss.mj.runipORfeg3Amk_A_sharp_ultra-clean_professional_por_bac47d6a-2088-4f84-8e9d-9d6f691b2889_1_9a818bd7.png",
    orientation: "portrait",
    tags: ["studio", "profile", "console", "epk"],
  },
  {
    id: "studio-profile-03",
    label: "Studio Profile 03",
    category: "epk",
    purpose: "Analog-session portrait for engineer and session-vocalist cards.",
    src: "/manus-storage/httpss.mj.runipORfeg3Amk_A_sharp_ultra-clean_professional_por_bac47d6a-2088-4f84-8e9d-9d6f691b2889_2_43c494bd.png",
    orientation: "portrait",
    tags: ["studio", "analog", "profile", "portrait"],
  },
  {
    id: "studio-profile-04",
    label: "Studio Profile 04",
    category: "epk",
    purpose: "Focused studio portrait for executive and technical credibility.",
    src: "/manus-storage/httpss.mj.runipORfeg3Amk_A_sharp_ultra-clean_professional_por_bac47d6a-2088-4f84-8e9d-9d6f691b2889_3_2bc54537.png",
    orientation: "portrait",
    tags: ["studio", "profile", "console", "cinematic"],
  },
  {
    id: "studio-profile-05",
    label: "Studio Profile 05",
    category: "epk",
    purpose: "Press-ready studio portrait for creative leadership surfaces.",
    src: "/manus-storage/httpss.mj.runipORfeg3Amk_A_sharp_ultra-clean_professional_por_fe4536d2-340b-4b01-b23e-5fb19bad03c3_0_3dd22199.png",
    orientation: "portrait",
    tags: ["studio", "profile", "mixing", "press"],
  },
  {
    id: "studio-profile-06",
    label: "Studio Profile 06",
    category: "epk",
    purpose: "Sharp profile image for talent, artist, and engineer cards.",
    src: "/manus-storage/httpss.mj.runipORfeg3Amk_A_sharp_ultra-clean_professional_por_fe4536d2-340b-4b01-b23e-5fb19bad03c3_1_80fb5144.png",
    orientation: "portrait",
    tags: ["studio", "profile", "shadow", "press"],
  },
  {
    id: "studio-profile-07",
    label: "Studio Profile 07",
    category: "epk",
    purpose: "Minimal portrait reference for black-box executive modules.",
    src: "/manus-storage/httpss.mj.runipORfeg3Amk_A_sharp_ultra-clean_professional_por_fe4536d2-340b-4b01-b23e-5fb19bad03c3_2_d8d43842.png",
    orientation: "portrait",
    tags: ["studio", "profile", "black", "executive"],
  },
  {
    id: "studio-profile-08",
    label: "Studio Profile 08",
    category: "epk",
    purpose: "High-contrast studio portrait for artist and executive profiles.",
    src: "/manus-storage/httpss.mj.runipORfeg3Amk_A_sharp_ultra-clean_professional_por_fe4536d2-340b-4b01-b23e-5fb19bad03c3_3_caa4282a.png",
    orientation: "portrait",
    tags: ["studio", "profile", "high-contrast", "executive"],
  },
  {
    id: "studio-wide",
    label: "Studio Wide Portrait",
    category: "epk",
    purpose: "Wide editorial portrait for portfolio and presentation headers.",
    src: "/manus-storage/httpss.mj.runipORfeg3Amk_httpss.mj.runZOqQyIW57tk_httpss.mj.r_91c97c96-4271-47b7-a5b2-94adbb150873_2_35ac0013.png",
    orientation: "landscape",
    tags: ["studio", "portrait", "wide", "cinematic"],
  },
  {
    id: "set-one",
    label: "Set One Contact Board",
    category: "cover",
    purpose: "Default cover-art system background when no artwork is supplied.",
    src: "/manus-storage/set1_ad9ff0b0.png",
    orientation: "landscape",
    tags: ["cover", "collage", "gold", "default"],
  },
  {
    id: "visual-dna-hero",
    label: "Visual DNA Hero Board",
    category: "editorial",
    purpose: "Primary Visuals vault hero treatment and brand reference board.",
    src: "/manus-storage/u5469791623_Create_the_following_5_hip_hop_photography_styles_67fc9871-4d1b-4bf7-b5f4-c95c6648ac34_2_5f599b77.png",
    orientation: "landscape",
    tags: ["hero", "visual-dna", "hype", "editorial"],
  },
  {
    id: "visual-dna-hero-02",
    label: "Visual DNA Hero Board 02",
    category: "cinematic",
    purpose: "Secondary cinematic board for Visuals and campaign surfaces.",
    src: "/manus-storage/u5469791623_Create_the_following_5_hip_hop_photography_styles_67fc9871-4d1b-4bf7-b5f4-c95c6648ac34_3_ec353227.png",
    orientation: "landscape",
    tags: ["hero", "visual-dna", "cinematic", "blue"],
  },
];

export const CURATED_HERO_ASSET = VISUAL_DNA_ASSETS.find(asset => asset.id === "visual-dna-hero")!;
export const CURATED_ROSTER_ASSETS = VISUAL_DNA_ASSETS.filter(asset => ["gold-chain-portrait", "portrait-board-01", "portrait-board-02", "studio-profile-01"].includes(asset.id));
export const CURATED_COVER_ASSETS = VISUAL_DNA_ASSETS.filter(asset => ["reflection-closeup", "jewel-shadow", "set-one", "saturated-board-02"].includes(asset.id));

export const VISUAL_ASSET_CATEGORIES: Array<{ id: VisualAssetCategory | "all"; label: string }> = [
  { id: "all", label: "All Visual DNA" },
  { id: "editorial", label: "Editorial / Hype" },
  { id: "epk", label: "EPK / Press" },
  { id: "lookbook", label: "Streetwear Lookbook" },
  { id: "cinematic", label: "Cinematic Stills" },
  { id: "cover", label: "Cover Templates" },
];
